### ISSUE TITLE
Bad configuration option: TCPRcvBufPoll

### ISSUE THREAD

**Issue by woodman250** [rapier1/openssh-portable#21]
I compiled latest release openssh-portable-hpn-ServerLog-8_1_P1.
After build completed, I tested file update, all was OK.
Then I add 3 options in sshd_config as below:

NoneEnabled yes
NoneSwitch yes
TCPRcvBufPoll yes

Then start sshd, the error is as below:
[root@gst openssh-hpn]# /download/openssh-hpn/sbin/sshd -f /download/openssh-hpn/etc/sshd_config
/download/openssh-hpn/etc/sshd_config: line 108: Bad configuration option: NoneEnabled
/download/openssh-hpn/etc/sshd_config: line 109: Bad configuration option: NoneSwitch
/download/openssh-hpn/etc/sshd_config: line 110: Bad configuration option: TCPRcvBufPoll
/download/openssh-hpn/etc/sshd_config: terminating, 3 bad configuration options

**Comment by rapier1** [comment]
The serverlog branch only contains code to enable more extensive server side logging for SSH. If you want to make use of the none switch, receiver side buffer polling, and such not you'll need to use the KitchenSink series of tags.
'git tag | grep Kitchen'
will give you a list of those versions.

Sorry that isn't clear in the directions.

**Comment by woodman250** [comment]
Thanks a lot. I built openssh-portable-hpn-KitchenSink-8_1_P1 that is what I need.

**Comment by panachoi** [comment]
Whats the difference between the hpn-8_1_P1 and hpn-KitchenSink-8_1_P1 tags, if any ?

**Comment by rapier1** [comment]
These are just different names for the same release. It's an artifact of how this was being released early on and I've just carried through on it.
