### ISSUE TITLE
config.h.in is missing causing ./configure to fail

### ISSUE THREAD

**Issue by davidcarver** [rapier1/openssh-portable#29]
staff.frontera(1034)$ pwd
/work/00108/dcarver/openssh2/isshd-8.1p1-hpn14.20-nersc3.19
staff.frontera(1035)$ autoconf
staff.frontera(1036)$ ./configure
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
...
config.status: creating openbsd-compat/Makefile
config.status: creating openbsd-compat/regress/Makefile
config.status: creating survey.sh
config.status: error: cannot find input file: `config.h.in'
staff.frontera(1037)$ 

I got ./configure to work by copying config.h.in from the base openssh-8.1p1, but I am not sure if was the correct solution for creating  config.h for isshd.

**Comment by vapier** [comment]
you've run `autoconf`, but the README says you have to use `autoreconf`.  the latter should generate the header file for you.
