### ISSUE TITLE
sshd segfaults on non-SMT machine after successful authentication - impossible to connect

### ISSUE THREAD

**Issue by S-trace** [rapier1/openssh-portable#35]
The sshd daemon running on a machine without SMT is accepting a connection but then falls into segmentation fault after successful authentication, which makes it useless as it is impossible to connect.

The problem is caused by 	/* determine is hyperthreading is enabled */ part of ssh_aes_ctr_init() in cipher-ctr-mt.c - it tries to open "/sys/devices/system/cpu/smt/active" for reading, but then incorrectly behaves if fopen() returned NULL, attempting to fscanf() from NULL pointer, which leads to segfault.

Fixed in https://github.com/rapier1/openssh-portable/pull/34

**Comment by rapier1** [comment]
Doh! Thanks for catching that. I never would have found that as I don't think I have any single core systems left to test that on. I'll pull that in asap.

**Comment by S-trace** [comment]
VIM2 is 8-cores non-SMT system. I'm happy to help you!

**Comment by rapier1** [comment]
Crazy! Anyway, I should have looked more closely at that chunk of my code before I pushed it out. Thanks again, 
Chris
