### ISSUE TITLE
Install order of operations problem

### ISSUE THREAD

**Issue by mpounsett** [rapier1/openssh-portable#42]
The `HPNSSHInstallation.txt` file puts the `make install` step before the creation of the privilege separation user, which causes an error during install in the `check-config` target.

```
/usr/local/sbin/hpnsshd -t -f /usr/local/etc/hpnssh/sshd_config
Privilege separation user hpnsshd does not exist
make: [Makefile:386: check-config] Error 255 (ignored)
```

This could be trivially fixed by swapping steps 7 and 8 in the document. 

I'm happy to do a PR if you agree that this change should be made.

**Comment by rapier1** [comment]
Oh crap. Sorry about that. Yes, please issue a PR and we'll incorporate that.
