### ISSUE TITLE
Adding HPN-SSH to openssh 8.4p1-5+deb11u1 (Debian Bullseye)

### ISSUE THREAD

**Issue by mpounsett** [rapier1/openssh-portable#45]
I'm having a hard time getting the patches to apply cleanly for Debian.  I have tried starting with the hpn-8_4_P1 tag from this repo and adding the standard suite of Debian patches to it, and have also tried taking the Debian source package and adding the Kitchen Sink patch to that.  Both result in patch conflicts and fail to compile.  

It looks like the Debian packages distributed from SourceForge are out of date (the latest is Buster).  

Is there a set of instructions somewhere I can follow in order to get this to build, or do I need to wait for a Bullseye package (or Bookworm, which is due out any minute now)?

**Comment by fscheiner** [comment]
For [the GCT](https://github.com/gridcf/gct) we maintain a version of OpenSSH that includes both [GSI authentication](https://gridcf.org/gct-docs/latest/gsic/key/index.html) (in addition to the standard SSH authentication) and HPN (v15.1 at the moment). As there is no GSI-OpenSSH in the official repositories for Debian GNU/Linux 11, I created a version that is based on the Debian version of OpenSSH that includes GSI and HPN.

How to use it is detailed in https://github.com/gridcf/gct/issues/170#issuecomment-1212018544.

HTH

**Comment by rapier1** [comment]
Also, apologies for the long delay in replying. I've been slammed with work trying to fix some memory issues in recent versions of hpn-ssh.

**Comment by rapier1** [comment]
Ah, I see what the problem is - the patches in the debian series really don't apply very well. So my suggestion is to grab gsissh like @fscheiner suggested if you want to stay on 8.4. If you want to get a more recent version I'll be looking at moving the Ubuntu package for 9.3 over to Ubuntu.

**Comment by mpounsett** [comment]
I'm not married to 8.4 .. I just picked it because it's the current version on Debian Buster.  I figured the Buster source package + the Kitchen Sink patch would be the easiest route to getting it working.  I'm happy to run a more recent version if you're already packaging that.

**Comment by rapier1** [comment]
I just put up a package for Bullseye at 
https://sourceforge.net/projects/hpnssh/files/

Could you give that a try? It's the most recent version of HPN-SSH 
(17v13) based on OpenSSH 9.3.

I have to get a better system in place for Debian.

Chris

**Comment by mpounsett** [comment]
Thanks Chris.  I won't be able to look at that before the weekend, but I'll check it out next week.
