### ISSUE TITLE
Possible to get binaries for Mac OS Ventura for apple silicon or home brew package?

### ISSUE THREAD

**Issue by anarchy89** [rapier1/openssh-portable#46]
I wanna try this out on my Mac mini and MacBook Pro (both apple silicon), is it possible to run a server and client for this on it? 

Is there a home brew package or binary I could install or some instructions I could follow?

**Comment by rapier1** [comment]
Packaging is hard. I haven't built a brew package yet but I'll get started
soon. That said, building from source isn't that hard. I can give you
directions for that if you like..

**Comment by rapier1** [comment]
As an aside, I can't get this to work with PAM. Still working on what's
going wrong with that. I don't think you'll need that though.

**Comment by rapier1** [comment]
As an aside we have an installation guide at https://www.psc.edu/hpn-ssh-home/hpn-ssh-installation/ It's not focused on OS X though. So there will be parts that don't correspond. The one downside is that the default crypto library on OSX is libressl 3.6 which doesn't support the threaded AES cipher. To get that you'd need to install openssl via brew. 

I'll start looking at brew in the next week or two. I'm still working through other packaging issues.

**Comment by anarchy89** [comment]
Is it available on brew yet ?

**Comment by rapier1** [comment]
Packaging is hard. I personally don't have the time to figure out how brew
works. I'm more than happy to take direction but all of my effort is
focused on improving the code base at this point. If someone can suggest a
recipe I'll try to submit it to the brew maintainers but, at the moment, we
are just two people.

**Comment by rapier1** [comment]
As a note: We will create a brew recipe and then try to get it submitted to the necessary maintainers. We just can't do it now and do not have a timeline for it. Which is why I'm closing this ticket as we simply can't respond to it in anything approaching a timely manner. 

TL:DR; We will work on this but I don't know when.
