### ISSUE TITLE
Integrate init.d script on installation instructions

### ISSUE THREAD

**Issue by gdevenyi** [rapier1/openssh-portable#48]
The install instructions page provides an example init.d script:
https://www.psc.edu/hpn-ssh-home/hpn-ssh-installation/

It turns out, there's an existing templated init.d script in the repository, which is used during build:
https://github.com/rapier1/openssh-portable/blob/master/opensshd.init.in

It gets the proper paths from the configuration substituted in.

This script could be patched, or using the same facilities the hpnssh.init script could be converted to a template and added to the build.

**Comment by rapier1** [comment]
The init script provided by openssh is functional. However, the ones provided in the installation directions are more flexible and provide coverage for both systemd and init.d environments. The one in the installation instructions should likely replace the one in the git repo though - that one is from 2005 or so. I'll add that to my todo list.

**Comment by rapier1** [comment]
First pass of this completed. This will be in the next release.
