### ISSUE TITLE
Clarify supported versions of OpenSSL

### ISSUE THREAD

**Issue by gdevenyi** [rapier1/openssh-portable#49]
The README should specify which versions of OpenSSL (another LibreSSL?) the code base supports.

In particular, some older codebases require 1.1.1 so its not clear to me here.

**Comment by rapier1** [comment]
I've changed the HPN-README to include the following. This will be part of the next release, 18v1.

OpenSSL Support:
Both OpenSSL 1.1.0g+ and OpenSSL 3.0+ are supported by HPN-SSH. Either one is
necessary to make use of the parallel ChaCha20-Poly1305 and AES-CTR ciphers as well
as the SCP resume feature. OpenSSL 1.0 and older are no longer supported. HPN-SSH can,
like OpenSSH, be compiled without OpenSSL (e.g. './configure --without-openssl')
but will only use of a limited set of internal cryptographic functions.

LibreSSL Support:
Changes in LibreSSL version 3.5 and 3.6 prevent the use of the threaded AES CTR cipher.
In those cases HPNSSH will fallback to the serial version of the AES CTR cipher. A warning
is printed to stderr. In all other cases LibreSSL will provide the same level
of functionality as OpenSSL 1.1.

**Comment by gdevenyi** [comment]
Thanks!
