### ISSUE TITLE
OpenSSH 9.3p2 tags missing

### ISSUE THREAD

**Issue by dave-re-imprivata** [rapier1/openssh-portable#52]
I know changes were merged to support 9.3p2 - but the associated tags appear to be missing? (ie, there's no V_9_3_P2 tag from upstream, etc). 

I know this is overloading the issue a bit - but any thoughts on availability of DynamicWindow patch tag for 9.3p2 or 9.4p1?

**Comment by rapier1** [comment]
Crap! Sorry about that. I've been overwhelmed with other issues and I completely overlooked this. I'll get to it tomorrow. I'll also be reviewing the Dynamic Window branch to ensure that it's up to date. Oh, in case I didn't mention it we are moving DynamicWindow to it's own branch as we are trying to cleanup how we use tags. 

9.4 will be available shortly. We are finalizing a major feature (parallel chacha20) and we need a little bit more time for that. I expect that to be done next week as we are just nailing down an edge case. I'll update the DynamicWindow at that time.

**Comment by dave-re-imprivata** [comment]
All good - I can run w/ 9.3p2 for a bit, and update to 9.4 once you release it. Just going through a quick refresh of a bunch of things while we start our next QA cycle - trying to pop this in at the beginning so we get plenty of test time!
