### ISSUE TITLE
MAC integrity failure

### ISSUE THREAD

**Issue by rapier1** [rapier1/openssh-portable#6]
mac hmac-ripemd160-etm@openssh.com is failing to pass the regression tests for the KitchenSink version of the code. There seems to be some sort of odd interaction that wasn't happening in 7.1p2. I believe it's some issue between the code for the none cipher switch and the aes_mt_ctr cipher. The aes-mt-ctr cipher works fine on it's own, it's only when that code set is incorporated with the null switch that we seem to have problems. As a work around please do not use ripemd160-etm until this issue is fixed.

**Comment by rapier1** [comment]
Well, it's not an interaction issue with the None cipher code as I see the same problem when I merge the AES-MT-CTR into the DynamicWindow tag. This is not an issue when only the AES_MT_CTR code set is applied.

**Comment by rapier1** [comment]
More data: If the integrity test is forced to use other ciphers then it passes as expected so it's specific to the way that the aes-ctr-mt cipher is being used. The problem is that I'm not sure how the integrity tests are being run so I need to look into this more deeply. If anyone has any suggestions please speak up.

**Comment by chutz** [comment]
I forward ported the patch to openssh-7.3p1 and this failure does not happen for me (dropping the server logging stuff). I suspect that it must be an upstream issue rather than something in the hpn patchset.

**Comment by rapier1** [comment]
I'll have to check that out. Also, thank you for the patches for CTR MT.

**Comment by vapier** [comment]
i've pushed updates for 7.3p1 to the repo and the tests are passing for me now
